baseURL: 'https://yuugouohno.github.io/ai-research-daily-sync'
languageCode: 'ja'
title: 'AI Research Daily'
theme: PaperMod

params:
  env: production
  title: "AI Research Daily"
  description: "毎日更新されるAI関連の技術記事とニュースの要約"
  
  homeInfoParams:
    Title: "AI Research Daily"
    Content: "最新のAI技術記事やニュースを毎日収集・要約しています。"

# Content organization
contentDir: "content"

# Markdown settings
markup:
  goldmark:
    renderer:
      unsafe: true

# Pagination
pagination:
  pagerSize: 10

# Build settings
buildDrafts: false
buildFuture: false